import type { Metadata } from "next";
import "../styles/globals.css";
import { inter, roboto, spaceGrotesk } from "@/styles/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${inter.variable} 
        ${spaceGrotesk.variable}
        ${roboto.variable}
        font-sans
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
